### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by bgilbert** [coreos/cap-std-ext#42]
```
error[E0425]: cannot find function `pipe` in module `rustix::io`
  --> tests/it/main.rs:17:30
   |
17 |     let (r, w) = rustix::io::pipe()?;
   |                              ^^^^ not found in `rustix::io`
```

**Comment by sunfishcode** [comment]
In rustix 0.38, the `pipe` function was moved to `rustix::pipe::pipe` and requires the "pipe" cargo feature.

**Comment by cgwalters** [comment]
I started to look at this (we have https://github.com/coreos/cap-std-ext/pull/40 outstanding) but now I have [bigger questions](https://github.com/bytecodealliance/cap-std/commit/963eebf3ab52b04a2e8b9ba88ce6308bbed5cbd0#r121651362)
